-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.data_studio_manufacturers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  production_manufacturer_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  website_url text,
  logo_url text,
  hero_image_url text,
  description text,
  abn text,
  phone text,
  status text NOT NULL DEFAULT 'draft'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  hero_image_position_y smallint NOT NULL DEFAULT 50 CHECK (hero_image_position_y >= 0 AND hero_image_position_y <= 100),
  pending_contact_full_name text,
  pending_contact_email_primary text,
  pending_contact_email_secondary text,
  pending_contact_login_preference text NOT NULL DEFAULT 'primary'::text CHECK (pending_contact_login_preference = ANY (ARRAY['primary'::text, 'secondary'::text])),
  hero_wide_image_url text,
  hero_wide_image_position_y smallint NOT NULL DEFAULT 50 CHECK (hero_wide_image_position_y >= 0 AND hero_wide_image_position_y <= 100),
  widget_button_config jsonb NOT NULL DEFAULT '{"show_find_stockist": true, "show_request_quote": true, "show_general_enquiry": true}'::jsonb,
  logo_asset_id uuid,
  hero_image_asset_id uuid,
  hero_wide_image_asset_id uuid,
  data_licence jsonb NOT NULL DEFAULT '{"status": "pending", "permissions": {"aiTraining": false, "aiRetrieval": false, "benchmarking": false, "publicSearch": false, "commercialRedistribution": false}}'::jsonb,
  CONSTRAINT data_studio_manufacturers_pkey PRIMARY KEY (id),
  CONSTRAINT data_studio_manufacturers_logo_asset_id_fkey FOREIGN KEY (logo_asset_id) REFERENCES public.manufacturer_assets(id),
  CONSTRAINT data_studio_manufacturers_hero_image_asset_id_fkey FOREIGN KEY (hero_image_asset_id) REFERENCES public.manufacturer_assets(id),
  CONSTRAINT data_studio_manufacturers_hero_wide_image_asset_id_fkey FOREIGN KEY (hero_wide_image_asset_id) REFERENCES public.manufacturer_assets(id)
);
CREATE TABLE public.data_studio_user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text,
  global_role text NOT NULL DEFAULT 'manufacturer_user'::text CHECK (global_role = ANY (ARRAY['buildquote_admin'::text, 'buildquote_reviewer'::text, 'manufacturer_user'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_email_primary text,
  company_email_secondary text,
  login_email_preference text NOT NULL DEFAULT 'primary'::text CHECK (login_email_preference = ANY (ARRAY['primary'::text, 'secondary'::text])),
  CONSTRAINT data_studio_user_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_document_id uuid NOT NULL,
  document_page_id uuid,
  extraction_run_id uuid,
  page_number integer,
  chunk_index integer NOT NULL,
  heading text,
  chunk_type text,
  raw_text text,
  table_json jsonb,
  docling_json jsonb,
  confidence numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT document_chunks_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES public.extraction_runs(id),
  CONSTRAINT document_chunks_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id),
  CONSTRAINT document_chunks_document_page_id_fkey FOREIGN KEY (document_page_id) REFERENCES public.document_pages(id)
);
CREATE TABLE public.document_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_document_id uuid NOT NULL,
  page_number integer NOT NULL,
  page_image_storage_key text,
  page_text text,
  docling_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_pages_pkey PRIMARY KEY (id),
  CONSTRAINT document_pages_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id)
);
CREATE TABLE public.extraction_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_document_id uuid NOT NULL,
  run_type text NOT NULL,
  status text NOT NULL DEFAULT 'queued'::text,
  tool_name text,
  tool_version text,
  model_name text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT extraction_runs_pkey PRIMARY KEY (id),
  CONSTRAINT extraction_runs_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id)
);
CREATE TABLE public.field_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  field_name text NOT NULL,
  extracted_value text,
  verified_value text,
  source_document_id uuid,
  source_page_id uuid,
  source_chunk_id uuid,
  source_page_number integer,
  status text NOT NULL DEFAULT 'pending'::text,
  confidence numeric,
  reviewer_id uuid,
  reviewed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT field_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT field_verifications_source_chunk_id_fkey FOREIGN KEY (source_chunk_id) REFERENCES public.document_chunks(id),
  CONSTRAINT field_verifications_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id),
  CONSTRAINT field_verifications_source_page_id_fkey FOREIGN KEY (source_page_id) REFERENCES public.document_pages(id)
);
CREATE TABLE public.manufacturer_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  auth_user_id uuid,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'manufacturer_reviewer'::text CHECK (role = ANY (ARRAY['manufacturer_admin'::text, 'manufacturer_reviewer'::text, 'manufacturer_viewer'::text])),
  status text NOT NULL DEFAULT 'invited'::text CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_profile_id uuid,
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  last_active_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT manufacturer_users_pkey PRIMARY KEY (id),
  CONSTRAINT fk_manufacturer_users_invited_by FOREIGN KEY (invited_by) REFERENCES public.data_studio_user_profiles(id),
  CONSTRAINT manufacturer_users_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT manufacturer_users_user_profile_id_fkey FOREIGN KEY (user_profile_id) REFERENCES public.data_studio_user_profiles(id)
);
CREATE TABLE public.parser_field_evidence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  extraction_run_id uuid NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  field_name text NOT NULL,
  extracted_value text,
  source_document_id uuid,
  source_page_number integer,
  source_chunk_id uuid,
  confidence numeric,
  is_uncertain boolean NOT NULL DEFAULT false,
  parser_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parser_field_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT parser_field_evidence_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES public.extraction_runs(id),
  CONSTRAINT parser_field_evidence_source_chunk_id_fkey FOREIGN KEY (source_chunk_id) REFERENCES public.document_chunks(id),
  CONSTRAINT parser_field_evidence_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id)
);
CREATE TABLE public.publish_batch_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  publish_batch_id uuid NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  production_table text,
  production_id uuid,
  status text NOT NULL DEFAULT 'pending'::text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  change_type text NOT NULL DEFAULT 'new'::text CHECK (change_type = ANY (ARRAY['new'::text, 'update'::text])),
  CONSTRAINT publish_batch_items_pkey PRIMARY KEY (id),
  CONSTRAINT publish_batch_items_publish_batch_id_fkey FOREIGN KEY (publish_batch_id) REFERENCES public.publish_batches(id)
);
CREATE TABLE public.publish_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid,
  status text NOT NULL DEFAULT 'draft'::text,
  export_type text NOT NULL DEFAULT 'csv'::text,
  production_project_ref text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_at timestamp with time zone,
  published_at timestamp with time zone,
  notes text,
  CONSTRAINT publish_batches_pkey PRIMARY KEY (id),
  CONSTRAINT publish_batches_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);
CREATE TABLE public.source_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  original_filename text NOT NULL,
  document_name text NOT NULL,
  document_type text,
  document_date text,
  storage_provider text NOT NULL DEFAULT 'cloudflare_r2'::text,
  storage_bucket text,
  storage_key text,
  public_url text,
  file_mime_type text,
  file_size_bytes bigint,
  status text NOT NULL DEFAULT 'uploaded'::text,
  uploaded_by uuid,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  production_catalogue_source_id uuid,
  source_url text,
  ingest_kind text NOT NULL DEFAULT 'upload'::text CHECK (ingest_kind = ANY (ARRAY['upload'::text, 'url_fetch'::text])),
  CONSTRAINT source_documents_pkey PRIMARY KEY (id),
  CONSTRAINT source_documents_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);
CREATE TABLE public.staged_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  source_document_id uuid,
  source_chunk_id uuid,
  production_component_id uuid,
  sku text,
  name text NOT NULL,
  description text,
  category text,
  uom text,
  length_mm numeric,
  width_mm numeric,
  height_mm numeric,
  thickness_mm numeric,
  depth_mm numeric,
  gauge_mm numeric,
  diameter_mm numeric,
  roll_m numeric,
  weight_kg numeric,
  pieces integer,
  material text,
  finish text,
  colour text,
  profile text,
  texture text,
  coverage_m2 numeric,
  sort_order integer NOT NULL DEFAULT 0,
  extraction_confidence numeric,
  verification_status text NOT NULL DEFAULT 'pending_review'::text,
  verified_by uuid,
  verified_at timestamp with time zone,
  reviewer_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  volume_ml numeric,
  weight_g numeric,
  pack_format text,
  supplier_pack_qty numeric,
  supplier_pack_uom text,
  supplier_pack_note text,
  parser_notes jsonb,
  image_url text,
  website_url text,
  extracted_at timestamp with time zone,
  procurement_route text,
  CONSTRAINT staged_components_pkey PRIMARY KEY (id),
  CONSTRAINT staged_components_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT staged_components_source_chunk_id_fkey FOREIGN KEY (source_chunk_id) REFERENCES public.document_chunks(id),
  CONSTRAINT staged_components_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id)
);
CREATE TABLE public.staged_system_colours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staged_system_id uuid NOT NULL,
  colour_name text NOT NULL,
  sku text,
  image_url text,
  is_stocked boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  verification_status text NOT NULL DEFAULT 'pending_review'::text,
  reviewer_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  parser_notes jsonb,
  sku_suffix text,
  extracted_at timestamp with time zone,
  production_colour_id uuid,
  image_asset_id uuid,
  CONSTRAINT staged_system_colours_pkey PRIMARY KEY (id),
  CONSTRAINT staged_system_colours_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id),
  CONSTRAINT staged_system_colours_image_asset_id_fkey FOREIGN KEY (image_asset_id) REFERENCES public.manufacturer_assets(id)
);
CREATE TABLE public.staged_system_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staged_system_id uuid NOT NULL,
  staged_component_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'component'::text,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  extraction_confidence numeric,
  verification_status text NOT NULL DEFAULT 'pending_review'::text,
  verified_by uuid,
  verified_at timestamp with time zone,
  reviewer_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  parser_notes jsonb,
  extracted_at timestamp with time zone,
  CONSTRAINT staged_system_components_pkey PRIMARY KEY (id),
  CONSTRAINT staged_system_components_staged_component_id_fkey FOREIGN KEY (staged_component_id) REFERENCES public.staged_components(id),
  CONSTRAINT staged_system_components_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.staged_system_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staged_system_id uuid NOT NULL,
  name text,
  product_code text,
  dimensions text,
  length_m numeric,
  sheet_format text,
  sort_order integer NOT NULL DEFAULT 0,
  verification_status text NOT NULL DEFAULT 'pending_review'::text,
  reviewer_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  profile_name text,
  length_mm numeric,
  width_mm numeric,
  height_mm numeric,
  thickness_mm numeric,
  depth_mm numeric,
  gauge_mm numeric,
  diameter_mm numeric,
  roll_m numeric,
  weight_kg numeric,
  pieces numeric,
  volume_ml numeric,
  weight_g numeric,
  pack_format text,
  supplier_pack_qty numeric,
  supplier_pack_uom text,
  supplier_pack_note text,
  bal_rating text,
  parser_notes jsonb,
  uom text,
  image_url text,
  website_url text,
  extracted_at timestamp with time zone,
  procurement_route text,
  production_profile_id uuid,
  description text,
  CONSTRAINT staged_system_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT staged_system_profiles_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.staged_systems (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  source_document_id uuid,
  source_chunk_id uuid,
  production_system_id uuid,
  name text NOT NULL,
  product_code text,
  slug text,
  category text,
  subcategory text,
  description text,
  dimensions text,
  length_m numeric,
  double_sided boolean NOT NULL DEFAULT false,
  hero_image_url text,
  website_url text,
  source_label text,
  source_url text,
  sheet_format text,
  fire_rating text,
  acoustic_rating text,
  moisture_resistant boolean NOT NULL DEFAULT false,
  structural_grade text,
  tech_data_url text,
  sort_order integer NOT NULL DEFAULT 0,
  extraction_confidence numeric,
  verification_status text NOT NULL DEFAULT 'pending_review'::text,
  verified_by uuid,
  verified_at timestamp with time zone,
  reviewer_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  parser_notes jsonb,
  bal_rating text,
  extracted_at timestamp with time zone,
  australian_made boolean,
  install_guide_urls jsonb,
  design_guide_url text,
  last_submitted_at timestamp with time zone,
  last_published_at timestamp with time zone,
  hero_image_position_x smallint NOT NULL DEFAULT 50 CHECK (hero_image_position_x >= 0 AND hero_image_position_x <= 100),
  hero_image_position_y smallint NOT NULL DEFAULT 50 CHECK (hero_image_position_y >= 0 AND hero_image_position_y <= 100),
  hero_image_asset_id uuid,
  gallery_images jsonb NOT NULL DEFAULT '[]'::jsonb,
  publish_status text NOT NULL DEFAULT 'draft'::text CHECK (publish_status = ANY (ARRAY['draft'::text, 'published'::text, 'published_with_changes'::text])),
  published_version text,
  owner_account_id uuid,
  custom_document_links jsonb,
  hero_image_zoom numeric NOT NULL DEFAULT 1 CHECK (hero_image_zoom >= 1::numeric AND hero_image_zoom <= 3::numeric),
  custom_technical_attributes jsonb,
  lifecycle_status text NOT NULL DEFAULT 'current'::text,
  search_aliases ARRAY,
  agent_ready_verified_at timestamp with time zone,
  agent_ready_verified_by uuid,
  agent_ready_notes text,
  CONSTRAINT staged_systems_pkey PRIMARY KEY (id),
  CONSTRAINT staged_systems_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT staged_systems_source_chunk_id_fkey FOREIGN KEY (source_chunk_id) REFERENCES public.document_chunks(id),
  CONSTRAINT staged_systems_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id),
  CONSTRAINT staged_systems_hero_image_asset_id_fkey FOREIGN KEY (hero_image_asset_id) REFERENCES public.manufacturer_assets(id)
);
CREATE TABLE public.verification_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  action text NOT NULL,
  field_name text,
  old_value text,
  new_value text,
  reviewer_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT verification_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workspace_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'manufacturer_reviewer'::text CHECK (role = ANY (ARRAY['manufacturer_admin'::text, 'manufacturer_reviewer'::text, 'manufacturer_viewer'::text])),
  token_hash text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'revoked'::text])),
  invited_by uuid,
  invited_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  accepted_at timestamp with time zone,
  CONSTRAINT workspace_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_workspace_invitations_invited_by FOREIGN KEY (invited_by) REFERENCES public.data_studio_user_profiles(id),
  CONSTRAINT workspace_invitations_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);
CREATE TABLE public.pipeline_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  document_id uuid,
  job_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  result jsonb,
  error_message text,
  log_lines ARRAY DEFAULT '{}'::text[],
  progress jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  worker_id text,
  heartbeat_at timestamp with time zone,
  CONSTRAINT pipeline_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.manufacturer_embed_widgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  public_token text NOT NULL DEFAULT encode(gen_random_bytes(24), 'hex'::text) UNIQUE,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT manufacturer_embed_widgets_pkey PRIMARY KEY (id),
  CONSTRAINT manufacturer_embed_widgets_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);
CREATE TABLE public.manufacturer_embed_widget_systems (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  embed_widget_id uuid NOT NULL,
  staged_system_id uuid NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT manufacturer_embed_widget_systems_pkey PRIMARY KEY (id),
  CONSTRAINT manufacturer_embed_widget_systems_embed_widget_id_fkey FOREIGN KEY (embed_widget_id) REFERENCES public.manufacturer_embed_widgets(id),
  CONSTRAINT manufacturer_embed_widget_systems_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.manufacturer_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  sender_type text NOT NULL CHECK (sender_type = ANY (ARRAY['manufacturer'::text, 'buildquote'::text])),
  sender_user_id uuid,
  sender_label text,
  body text NOT NULL,
  message_type text NOT NULL DEFAULT 'general'::text CHECK (message_type = ANY (ARRAY['general'::text, 'help'::text, 'submission'::text, 'ai_question'::text])),
  related_publish_batch_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  acknowledged_at timestamp with time zone,
  CONSTRAINT manufacturer_messages_pkey PRIMARY KEY (id),
  CONSTRAINT manufacturer_messages_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT manufacturer_messages_related_publish_batch_id_fkey FOREIGN KEY (related_publish_batch_id) REFERENCES public.publish_batches(id)
);
CREATE TABLE public.widget_quote_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  widget_id uuid,
  system_id text NOT NULL,
  system_name text,
  selected_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  postcode text,
  project_type text CHECK (project_type = ANY (ARRAY['residential'::text, 'commercial'::text, 'other'::text])),
  timeline text CHECK (timeline = ANY (ARRAY['asap'::text, '1-3months'::text, 'planning'::text])),
  message text,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'viewed'::text, 'responded'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT widget_quote_requests_pkey PRIMARY KEY (id),
  CONSTRAINT widget_quote_requests_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT widget_quote_requests_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES public.manufacturer_embed_widgets(id)
);
CREATE TABLE public.manufacturer_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  asset_type text NOT NULL CHECK (asset_type = ANY (ARRAY['logo'::text, 'brand_hero'::text, 'banner'::text, 'card_hero'::text, 'profile'::text, 'product'::text, 'thumbnail'::text, 'icon'::text])),
  title text,
  alt_text text,
  caption text,
  storage_key text,
  source_url text,
  public_url text,
  mime_type text,
  file_size_bytes bigint,
  width integer,
  height integer,
  focal_x smallint NOT NULL DEFAULT 50 CHECK (focal_x >= 0 AND focal_x <= 100),
  focal_y smallint NOT NULL DEFAULT 50 CHECK (focal_y >= 0 AND focal_y <= 100),
  approved_for_publication boolean NOT NULL DEFAULT false,
  archived boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  staged_system_id uuid,
  asset_role text,
  CONSTRAINT manufacturer_assets_pkey PRIMARY KEY (id),
  CONSTRAINT manufacturer_assets_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT manufacturer_assets_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.card_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  package_version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'generating'::text CHECK (status = ANY (ARRAY['generating'::text, 'generated'::text, 'downloaded'::text, 'failed'::text, 'superseded'::text])),
  intended_install_path text NOT NULL DEFAULT '/system-cards/'::text,
  zip_storage_key text,
  zip_url text,
  manifest_url text,
  feed_url text,
  preview_url text,
  checksum text,
  file_size_bytes bigint,
  card_count integer NOT NULL DEFAULT 0,
  error_message text,
  build_log text,
  generated_at timestamp with time zone,
  generated_by uuid,
  downloaded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT card_packages_pkey PRIMARY KEY (id),
  CONSTRAINT card_packages_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);
CREATE TABLE public.card_package_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL,
  card_id uuid NOT NULL,
  package_slug text NOT NULL,
  generated_card_path text,
  generated_json_path text,
  qr_code_path text,
  status text NOT NULL DEFAULT 'included'::text CHECK (status = ANY (ARRAY['included'::text, 'skipped'::text, 'failed'::text])),
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT card_package_items_pkey PRIMARY KEY (id),
  CONSTRAINT card_package_items_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.card_packages(id),
  CONSTRAINT card_package_items_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.manufacturer_stockists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  business_name text NOT NULL,
  suburb text,
  state text,
  phone text,
  website_url text,
  trade_desk_email text,
  all_cards boolean NOT NULL DEFAULT true,
  confirm_token uuid NOT NULL DEFAULT gen_random_uuid(),
  confirm_status text NOT NULL DEFAULT 'unconfirmed'::text CHECK (confirm_status = ANY (ARRAY['unconfirmed'::text, 'confirmed'::text])),
  confirmed_at timestamp with time zone,
  archived boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT manufacturer_stockists_pkey PRIMARY KEY (id),
  CONSTRAINT manufacturer_stockists_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);
CREATE TABLE public.manufacturer_stockist_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stockist_id uuid NOT NULL,
  card_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT manufacturer_stockist_cards_pkey PRIMARY KEY (id),
  CONSTRAINT manufacturer_stockist_cards_stockist_id_fkey FOREIGN KEY (stockist_id) REFERENCES public.manufacturer_stockists(id),
  CONSTRAINT manufacturer_stockist_cards_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.card_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  card_id uuid NOT NULL,
  package_id uuid,
  version integer NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  card_json jsonb NOT NULL,
  stockists_json jsonb,
  validated_by text,
  validated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  content_md text,
  content_hash text,
  sources_json jsonb,
  knowledge_json jsonb,
  CONSTRAINT card_versions_pkey PRIMARY KEY (id),
  CONSTRAINT card_versions_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT card_versions_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.staged_systems(id),
  CONSTRAINT card_versions_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.card_packages(id)
);
CREATE TABLE public.card_share_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  card_id uuid,
  card_slug text NOT NULL,
  token text NOT NULL,
  channel text NOT NULL DEFAULT 'copy'::text CHECK (channel = ANY (ARRAY['copy'::text, 'sms'::text, 'email'::text])),
  sender_tag text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT card_share_links_pkey PRIMARY KEY (id),
  CONSTRAINT card_share_links_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT card_share_links_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.card_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  card_id uuid,
  card_slug text NOT NULL,
  version integer,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['view'::text, 'share_open'::text, 'doc_click'::text])),
  channel text,
  sender_tag text,
  share_token text,
  host_domain text,
  doc_label text,
  doc_url text,
  device_hash text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT card_events_pkey PRIMARY KEY (id),
  CONSTRAINT card_events_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT card_events_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.system_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  staged_system_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['install_guide'::text, 'design_guide'::text, 'website'::text, 'tech_data'::text, 'source_catalogue'::text])),
  label text,
  url text NOT NULL,
  source_document_id uuid,
  ingest_status text NOT NULL DEFAULT 'linked'::text CHECK (ingest_status = ANY (ARRAY['linked'::text, 'queued'::text, 'fetching'::text, 'extracted'::text, 'failed'::text, 'skipped'::text])),
  include_in_container boolean NOT NULL DEFAULT true,
  error_message text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  ai_summary text,
  ai_summary_generated_at timestamp with time zone,
  CONSTRAINT system_sources_pkey PRIMARY KEY (id),
  CONSTRAINT system_sources_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT system_sources_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id),
  CONSTRAINT system_sources_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id)
);
CREATE TABLE public.card_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  card_id uuid NOT NULL,
  version integer NOT NULL,
  chunk_index integer NOT NULL,
  source_role text,
  page_start integer,
  page_end integer,
  content text NOT NULL,
  embedding USER-DEFINED NOT NULL,
  content_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT card_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT card_embeddings_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT card_embeddings_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.card_publish_events (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  card_id uuid NOT NULL,
  event_type text NOT NULL,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  meta jsonb,
  CONSTRAINT card_publish_events_pkey PRIMARY KEY (id),
  CONSTRAINT card_publish_events_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.manufacturer_link_library (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  label text NOT NULL,
  url text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT manufacturer_link_library_pkey PRIMARY KEY (id),
  CONSTRAINT manufacturer_link_library_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);
CREATE TABLE public.knowledge_assertions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  staged_system_id uuid,
  subject_kind text NOT NULL,
  subject_ref uuid,
  subject_local_id text,
  predicate text NOT NULL,
  object_kind text NOT NULL,
  object_value jsonb NOT NULL,
  claim_type text NOT NULL DEFAULT 'unknown'::text,
  origin text NOT NULL,
  epistemic_status text NOT NULL DEFAULT 'unverified'::text,
  answer_policy text,
  confidence numeric,
  derivation jsonb,
  supersedes_assertion_id uuid,
  inherited_from_assertion_id uuid,
  extraction_run_id uuid,
  verified_by uuid,
  verified_at timestamp with time zone,
  evidence_refreshed_at timestamp with time zone,
  review_horizon date,
  reviewer_notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_assertions_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_assertions_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT knowledge_assertions_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id),
  CONSTRAINT knowledge_assertions_supersedes_assertion_id_fkey FOREIGN KEY (supersedes_assertion_id) REFERENCES public.knowledge_assertions(id),
  CONSTRAINT knowledge_assertions_inherited_from_assertion_id_fkey FOREIGN KEY (inherited_from_assertion_id) REFERENCES public.knowledge_assertions(id),
  CONSTRAINT knowledge_assertions_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES public.extraction_runs(id)
);
CREATE TABLE public.assertion_evidence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assertion_id uuid NOT NULL,
  source_kind text NOT NULL DEFAULT 'document'::text,
  source_document_id uuid,
  system_source_id uuid,
  document_chunk_id uuid,
  page_start integer,
  page_end integer,
  locator text,
  quote text,
  source_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assertion_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT assertion_evidence_assertion_id_fkey FOREIGN KEY (assertion_id) REFERENCES public.knowledge_assertions(id),
  CONSTRAINT assertion_evidence_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES public.source_documents(id),
  CONSTRAINT assertion_evidence_system_source_id_fkey FOREIGN KEY (system_source_id) REFERENCES public.system_sources(id),
  CONSTRAINT assertion_evidence_document_chunk_id_fkey FOREIGN KEY (document_chunk_id) REFERENCES public.document_chunks(id)
);
CREATE TABLE public.system_relationships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manufacturer_id uuid NOT NULL,
  staged_system_id uuid NOT NULL,
  relation text NOT NULL,
  target_staged_system_id uuid,
  target_external jsonb,
  note text,
  reason text,
  epistemic_status text NOT NULL DEFAULT 'manufacturer_supplied'::text,
  verified_by uuid,
  verified_at timestamp with time zone,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_relationships_pkey PRIMARY KEY (id),
  CONSTRAINT system_relationships_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id),
  CONSTRAINT system_relationships_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id),
  CONSTRAINT system_relationships_target_staged_system_id_fkey FOREIGN KEY (target_staged_system_id) REFERENCES public.staged_systems(id)
);
CREATE TABLE public.knowledge_taxonomy_terms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  domain text NOT NULL,
  slug text NOT NULL,
  label text NOT NULL,
  CONSTRAINT knowledge_taxonomy_terms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_knowledge_gaps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'NEW'::text CHECK (status = ANY (ARRAY['NEW'::text, 'TRIAGED'::text, 'AWAITING_MANUFACTURER'::text, 'MANUFACTURER_RESPONDED'::text, 'AWAITING_VERIFICATION'::text, 'RESOLVED'::text, 'PUBLISHED'::text, 'DUPLICATE'::text, 'OUT_OF_SCOPE'::text, 'NO_ACTION_REQUIRED'::text, 'ESCALATED'::text])),
  failure_type text CHECK (failure_type IS NULL OR (failure_type = ANY (ARRAY['KNOWLEDGE_GAP'::text, 'RETRIEVAL_GAP'::text, 'TERMINOLOGY_GAP'::text, 'RELATIONSHIP_GAP'::text, 'VERIFICATION_GAP'::text, 'AMBIGUOUS_QUERY'::text, 'OUT_OF_SCOPE'::text, 'SCHEMA_GAP'::text]))),
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'safety_critical'::text])),
  user_question text NOT NULL,
  normalised_question jsonb,
  staged_system_id uuid,
  manufacturer_id uuid,
  anon_session_id text,
  builder_user_id uuid,
  ai_response_status text NOT NULL CHECK (ai_response_status = ANY (ARRAY['NO_VERIFIED_ANSWER'::text, 'ANSWERED_WITH_CAVEAT'::text])),
  retrieval_summary jsonb,
  matched_assertion_ids ARRAY,
  missing_information text,
  repeat_count integer NOT NULL DEFAULT 1,
  cluster_id uuid,
  manufacturer_response jsonb,
  resolution_type text CHECK (resolution_type IS NULL OR (resolution_type = ANY (ARRAY['confirmed_yes'::text, 'confirmed_no'::text, 'conditional'::text, 'info_not_available'::text, 'needs_review'::text]))),
  resulting_assertion_ids ARRAY,
  resolution_notes text,
  assigned_to uuid,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  manufacturer_verification_required boolean NOT NULL DEFAULT true,
  CONSTRAINT ai_knowledge_gaps_pkey PRIMARY KEY (id),
  CONSTRAINT ai_knowledge_gaps_staged_system_id_fkey FOREIGN KEY (staged_system_id) REFERENCES public.staged_systems(id),
  CONSTRAINT ai_knowledge_gaps_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.data_studio_manufacturers(id)
);