// Mock parser output fixtures for BuildQuote Data Studio.
//
// These are realistic example parser outputs used for:
//   - type-checking the parser contract
//   - testing the insertion layer (when built)
//   - driving the parser result preview UI (when built)
//
// No Supabase client. No database writes. No AI calls. No file uploads.
// All IDs are fake placeholder UUIDs — not real stored documents or chunks.

import type {
  ParserOutput,
  ParsedFieldSource,
} from './types'

// ----------------------------------------------------------
// Fake placeholder IDs
// Real runs will have genuine UUIDs from the DB.
// ----------------------------------------------------------

const DOC_NTW = 'aaaaaaaa-0001-0000-0000-000000000001'
const DOC_JH  = 'aaaaaaaa-0002-0000-0000-000000000001'
const DOC_WRAP = 'aaaaaaaa-0003-0000-0000-000000000001'

const CHUNK_NTW_COVER    = 'cccccccc-0001-0000-0000-000000000001'
const CHUNK_NTW_PROFILES = 'cccccccc-0001-0000-0000-000000000002'
const CHUNK_NTW_CLIPS    = 'cccccccc-0001-0000-0000-000000000003'
const CHUNK_NTW_COLOURS  = 'cccccccc-0001-0000-0000-000000000004'

const CHUNK_JH_COVER    = 'cccccccc-0002-0000-0000-000000000001'
const CHUNK_JH_PROFILES = 'cccccccc-0002-0000-0000-000000000002'
const CHUNK_JH_SCREWS   = 'cccccccc-0002-0000-0000-000000000003'

const CHUNK_WRAP_COVER   = 'cccccccc-0003-0000-0000-000000000001'
const CHUNK_WRAP_SPECS   = 'cccccccc-0003-0000-0000-000000000002'
const CHUNK_WRAP_TAPE    = 'cccccccc-0003-0000-0000-000000000003'

// ----------------------------------------------------------
// Helper: build a field source entry
// ----------------------------------------------------------

function src(
  field_name: string,
  extracted_value: string | null,
  source_page_number: number | null,
  source_chunk_id: string | null,
  confidence: number,
  opts?: { is_uncertain?: boolean; parser_note?: string }
): ParsedFieldSource {
  return {
    field_name,
    extracted_value,
    source_page_number,
    source_chunk_id,
    confidence,
    ...(opts?.is_uncertain !== undefined ? { is_uncertain: opts.is_uncertain } : {}),
    ...(opts?.parser_note ? { parser_note: opts.parser_note } : {}),
  }
}

// ----------------------------------------------------------
// Fixture 1: NewTechWood Avenue Decking
//
// Composite decking system. Exercises:
//   - multiple board profiles (5400mm and 2900mm)
//   - components: clip (pack size separate from uom), fascia board,
//     edge trim (components not profiles), screws
//   - colour sku_suffix convention
//   - system hero image, profile image, clip image, install diagram
// ----------------------------------------------------------

export const mockNTWAvenueDecking: ParserOutput = {
  source_document_id: DOC_NTW,

  systems: [
    {
      temp_key: 'system_0',
      source_document_id: DOC_NTW,
      source_chunk_id: CHUNK_NTW_COVER,
      source_page_number: 2,
      name: 'Avenue Decking',
      product_code: 'NTW-AVE',
      slug: null,
      category: 'Decking',
      subcategory: 'Composite',
      description:
        'Co-extrusion composite decking with solid core, available in grooved and smooth face options.',
      bal_rating: null,
      acoustic_rating: null,
      moisture_resistant: true,
      structural_grade: null,
      double_sided: false,
      sheet_format: null,
      install_guide_urls: null,
      tech_data_url: null,
      notes: null,
      sort_order: 0,
      extraction_confidence: 0.93,
      field_sources: [
        src('name', 'Avenue Decking', 2, CHUNK_NTW_COVER, 0.96),
        src('product_code', 'NTW-AVE', 2, CHUNK_NTW_COVER, 0.91),
        src('category', 'Decking', 2, CHUNK_NTW_COVER, 0.94),
        src('subcategory', 'Composite', 2, CHUNK_NTW_COVER, 0.88),
        src('description', 'Co-extrusion composite decking with solid core, available in grooved and smooth face options.', 2, CHUNK_NTW_COVER, 0.85),
        src('moisture_resistant', 'true', 3, CHUNK_NTW_COVER, 0.82),
        src('double_sided', 'false', 3, CHUNK_NTW_COVER, 0.79),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
  ],

  system_profiles: [
    {
      temp_key: 'profile_0',
      system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      name: 'Avenue Grooved Board 5400mm',
      profile_name: 'Avenue 5400',
      product_code: 'NTW-AVE-5400-GR',
      dimensions: '5400 x 138 x 29 mm',
      length_mm: 5400,
      width_mm: 138,
      thickness_mm: 29,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: 8.4,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      uom: 'lm',
      pack_format: 'Bundle',
      supplier_pack_qty: 10,
      supplier_pack_uom: 'boards',
      supplier_pack_note: null,
      bal_rating: 'BAL-12.5',
      sort_order: 0,
      source_page_number: 4,
      source_chunk_id: CHUNK_NTW_PROFILES,
      extraction_confidence: 0.91,
      field_sources: [
        src('profile_name', 'Avenue 5400', 4, CHUNK_NTW_PROFILES, 0.93),
        src('name', 'Avenue Grooved Board 5400mm', 4, CHUNK_NTW_PROFILES, 0.90),
        src('product_code', 'NTW-AVE-5400-GR', 4, CHUNK_NTW_PROFILES, 0.95),
        src('length_mm', '5400', 4, CHUNK_NTW_PROFILES, 0.97),
        src('width_mm', '138', 4, CHUNK_NTW_PROFILES, 0.97),
        src('thickness_mm', '29', 4, CHUNK_NTW_PROFILES, 0.95),
        src('weight_kg', '8.4', 4, CHUNK_NTW_PROFILES, 0.84),
        src('uom', 'lm', 4, CHUNK_NTW_PROFILES, 0.88),
        src('supplier_pack_qty', '10', 5, CHUNK_NTW_PROFILES, 0.86),
        src('supplier_pack_uom', 'boards', 5, CHUNK_NTW_PROFILES, 0.84),
        src('bal_rating', 'BAL-12.5', 6, CHUNK_NTW_PROFILES, 0.90),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
    {
      temp_key: 'profile_1',
      system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      name: 'Avenue Grooved Board 2900mm',
      profile_name: 'Avenue 2900',
      product_code: 'NTW-AVE-2900-GR',
      dimensions: '2900 x 138 x 29 mm',
      length_mm: 2900,
      width_mm: 138,
      thickness_mm: 29,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: 4.5,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      uom: 'lm',
      pack_format: 'Bundle',
      supplier_pack_qty: 20,
      supplier_pack_uom: 'boards',
      supplier_pack_note: null,
      bal_rating: 'BAL-12.5',
      sort_order: 1,
      source_page_number: 4,
      source_chunk_id: CHUNK_NTW_PROFILES,
      extraction_confidence: 0.90,
      field_sources: [
        src('profile_name', 'Avenue 2900', 4, CHUNK_NTW_PROFILES, 0.92),
        src('length_mm', '2900', 4, CHUNK_NTW_PROFILES, 0.97),
        src('width_mm', '138', 4, CHUNK_NTW_PROFILES, 0.97),
        src('thickness_mm', '29', 4, CHUNK_NTW_PROFILES, 0.95),
        src('uom', 'lm', 4, CHUNK_NTW_PROFILES, 0.88),
        src('supplier_pack_qty', '20', 5, CHUNK_NTW_PROFILES, 0.85),
        src('bal_rating', 'BAL-12.5', 6, CHUNK_NTW_PROFILES, 0.90),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
  ],

  components: [
    {
      // Hidden fix clip — component, not a profile
      temp_key: 'component_0',
      source_document_id: DOC_NTW,
      source_chunk_id: CHUNK_NTW_CLIPS,
      source_page_number: 8,
      sku: 'NTW-TC28-SS',
      name: 'TC28 Hidden Fix Clip',
      description: 'Stainless steel 304 hidden fix clip for composite decking installation.',
      category: 'Fixings',
      uom: 'ea',
      dimensions: null,
      length_mm: null,
      width_mm: null,
      height_mm: null,
      thickness_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: null,
      weight_g: 4.2,
      volume_ml: null,
      pieces: null,
      length_m: null,
      pack_format: 'Box',
      supplier_pack_qty: 100,
      supplier_pack_uom: 'clips',
      supplier_pack_note: 'Manufacturer full box; supplier may sell partial packs',
      material: 'Stainless steel 304',
      finish: null,
      colour: null,
      profile: null,
      texture: null,
      coverage_m2: null,
      sort_order: 0,
      extraction_confidence: 0.93,
      field_sources: [
        src('name', 'TC28 Hidden Fix Clip', 8, CHUNK_NTW_CLIPS, 0.95),
        src('sku', 'NTW-TC28-SS', 8, CHUNK_NTW_CLIPS, 0.93),
        src('category', 'Fixings', 8, CHUNK_NTW_CLIPS, 0.90),
        src('uom', 'ea', 8, CHUNK_NTW_CLIPS, 0.87),
        src('supplier_pack_qty', '100', 8, CHUNK_NTW_CLIPS, 0.92),
        src('supplier_pack_uom', 'clips', 8, CHUNK_NTW_CLIPS, 0.89),
        src('weight_g', '4.2', 8, CHUNK_NTW_CLIPS, 0.78),
        src('material', 'Stainless steel 304', 8, CHUNK_NTW_CLIPS, 0.91),
      ],
      parser_notes: [
        'Pack size of 100 is manufacturer full-box quantity — not builder order quantity.',
      ],
      uncertain_fields: [],
    },
    {
      // Fascia board — component, not a profile
      temp_key: 'component_1',
      source_document_id: DOC_NTW,
      source_chunk_id: CHUNK_NTW_CLIPS,
      source_page_number: 9,
      sku: 'NTW-AVE-FASCIA',
      name: 'Avenue Fascia Board',
      description: 'Matching fascia/edge board for Avenue Decking perimeter finish.',
      category: 'Trims',
      uom: 'lm',
      dimensions: '5400 x 138 x 10 mm',
      length_mm: 5400,
      width_mm: 138,
      thickness_mm: 10,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: null,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      pack_format: null,
      supplier_pack_qty: null,
      supplier_pack_uom: null,
      supplier_pack_note: null,
      material: null,
      finish: null,
      colour: null,
      profile: null,
      texture: null,
      coverage_m2: null,
      sort_order: 1,
      extraction_confidence: 0.88,
      field_sources: [
        src('name', 'Avenue Fascia Board', 9, CHUNK_NTW_CLIPS, 0.91),
        src('sku', 'NTW-AVE-FASCIA', 9, CHUNK_NTW_CLIPS, 0.90),
        src('category', 'Trims', 9, CHUNK_NTW_CLIPS, 0.87),
        src('uom', 'lm', 9, CHUNK_NTW_CLIPS, 0.85),
        src('length_mm', '5400', 9, CHUNK_NTW_CLIPS, 0.94),
        src('width_mm', '138', 9, CHUNK_NTW_CLIPS, 0.92),
        src('thickness_mm', '10', 9, CHUNK_NTW_CLIPS, 0.90),
      ],
      parser_notes: [
        'Fascia board classified as component (Trims) — not a system profile variant.',
      ],
      uncertain_fields: [],
    },
    {
      // Edge/starter trim — component, not a profile
      temp_key: 'component_2',
      source_document_id: DOC_NTW,
      source_chunk_id: CHUNK_NTW_CLIPS,
      source_page_number: 9,
      sku: 'NTW-AVE-EDGE',
      name: 'Avenue Edge Trim',
      description: 'Aluminium edge trim for Avenue Decking perimeter.',
      category: 'Trims',
      uom: 'lm',
      dimensions: '3600 mm length',
      length_mm: 3600,
      width_mm: null,
      thickness_mm: null,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: null,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      pack_format: null,
      supplier_pack_qty: null,
      supplier_pack_uom: null,
      supplier_pack_note: null,
      material: 'Aluminium',
      finish: null,
      colour: null,
      profile: null,
      texture: null,
      coverage_m2: null,
      sort_order: 2,
      extraction_confidence: 0.85,
      field_sources: [
        src('name', 'Avenue Edge Trim', 9, CHUNK_NTW_CLIPS, 0.90),
        src('category', 'Trims', 9, CHUNK_NTW_CLIPS, 0.86),
        src('uom', 'lm', 9, CHUNK_NTW_CLIPS, 0.83),
        src('length_mm', '3600', 9, CHUNK_NTW_CLIPS, 0.88),
        src('material', 'Aluminium', 9, CHUNK_NTW_CLIPS, 0.84),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
    {
      // Decking screws — component with pack size separate from uom
      temp_key: 'component_3',
      source_document_id: DOC_NTW,
      source_chunk_id: CHUNK_NTW_CLIPS,
      source_page_number: 10,
      sku: 'NTW-SCR-50',
      name: 'Stainless Steel Decking Screw 50mm',
      description: 'Stainless steel 316 self-drilling screw for composite decking fascia fixing.',
      category: 'Fixings',
      uom: 'ea',
      dimensions: '50mm length',
      length_mm: 50,
      width_mm: null,
      thickness_mm: null,
      height_mm: null,
      depth_mm: null,
      gauge_mm: 8,
      diameter_mm: null,
      roll_m: null,
      weight_kg: null,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      pack_format: 'Box',
      supplier_pack_qty: 200,
      supplier_pack_uom: 'screws',
      supplier_pack_note: null,
      material: 'Stainless steel 316',
      finish: null,
      colour: null,
      profile: null,
      texture: null,
      coverage_m2: null,
      sort_order: 3,
      extraction_confidence: 0.87,
      field_sources: [
        src('name', 'Stainless Steel Decking Screw 50mm', 10, CHUNK_NTW_CLIPS, 0.92),
        src('sku', 'NTW-SCR-50', 10, CHUNK_NTW_CLIPS, 0.89),
        src('uom', 'ea', 10, CHUNK_NTW_CLIPS, 0.84),
        src('gauge_mm', '8', 10, CHUNK_NTW_CLIPS, 0.76, {
          is_uncertain: true,
          parser_note: 'Source states "8g screw" — no mm equivalent extracted; gauge_mm set to 8 as label value only.',
        }),
        src('length_mm', '50', 10, CHUNK_NTW_CLIPS, 0.91),
        src('supplier_pack_qty', '200', 10, CHUNK_NTW_CLIPS, 0.90),
        src('supplier_pack_uom', 'screws', 10, CHUNK_NTW_CLIPS, 0.88),
      ],
      parser_notes: [
        'gauge_mm set to 8 from source "8g" — this is a gauge label, not mm. Review before export.',
      ],
      uncertain_fields: ['gauge_mm'],
    },
  ],

  system_components: [
    {
      temp_key: 'link_0',
      staged_system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      component_match: { sku: 'NTW-TC28-SS', name: 'TC28 Hidden Fix Clip' },
      role: 'required',
      notes: 'Hidden fix clip — install between boards at each joist. Category: Fixings.',
      sort_order: 0,
      extraction_confidence: 0.88,
      source_page_number: 8,
      source_chunk_id: CHUNK_NTW_CLIPS,
    },
    {
      temp_key: 'link_1',
      staged_system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      component_match: { sku: 'NTW-AVE-FASCIA', name: 'Avenue Fascia Board' },
      role: 'optional',
      notes: 'Perimeter fascia finish. Category: Trims.',
      sort_order: 1,
      extraction_confidence: 0.85,
      source_page_number: 9,
      source_chunk_id: CHUNK_NTW_CLIPS,
    },
    {
      temp_key: 'link_2',
      staged_system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      component_match: { sku: 'NTW-AVE-EDGE', name: 'Avenue Edge Trim' },
      role: 'optional',
      notes: 'Perimeter edge trim. Category: Trims.',
      sort_order: 2,
      extraction_confidence: 0.84,
      source_page_number: 9,
      source_chunk_id: CHUNK_NTW_CLIPS,
    },
    {
      temp_key: 'link_3',
      staged_system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      component_match: { sku: 'NTW-SCR-50', name: 'Stainless Steel Decking Screw 50mm' },
      role: 'accessory',
      notes: 'For fascia fixing. Category: Fixings.',
      sort_order: 3,
      extraction_confidence: 0.83,
      source_page_number: 10,
      source_chunk_id: CHUNK_NTW_CLIPS,
    },
  ],

  system_colours: [
    {
      temp_key: 'colour_0',
      system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      colour_name: 'Teak',
      sku: null,
      sku_suffix: '-TEK',
      is_stocked: true,
      sort_order: 0,
      source_page_number: 5,
      source_chunk_id: CHUNK_NTW_COLOURS,
      extraction_confidence: 0.92,
    },
    {
      temp_key: 'colour_1',
      system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      colour_name: 'Antique',
      sku: null,
      sku_suffix: '-ANT',
      is_stocked: true,
      sort_order: 1,
      source_page_number: 5,
      source_chunk_id: CHUNK_NTW_COLOURS,
      extraction_confidence: 0.92,
    },
    {
      temp_key: 'colour_2',
      system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      colour_name: 'Ipe',
      sku: null,
      sku_suffix: '-IPE',
      is_stocked: true,
      sort_order: 2,
      source_page_number: 5,
      source_chunk_id: CHUNK_NTW_COLOURS,
      extraction_confidence: 0.91,
    },
    {
      temp_key: 'colour_3',
      system_match: { system_name: 'Avenue Decking', product_code: 'NTW-AVE' },
      colour_name: 'Silver',
      sku: null,
      sku_suffix: '-SLV',
      is_stocked: false,
      sort_order: 3,
      source_page_number: 5,
      source_chunk_id: CHUNK_NTW_COLOURS,
      extraction_confidence: 0.88,
    },
  ],

  media: {
    images: [
      {
        // System hero image candidate
        source_document_id: DOC_NTW,
        source_page_number: 1,
        source_chunk_id: CHUNK_NTW_COVER,
        image_url: null,
        caption: 'Avenue Decking installed on residential deck',
        alt_text: 'NewTechWood Avenue composite decking — Teak colour',
        suggested_usage: 'hero_system',
        entity_temp_key: 'system_0',
        confidence: 0.85,
        parser_note: 'Full-page cover photo; no URL present in document.',
      },
      {
        // Profile/product image candidate
        source_document_id: DOC_NTW,
        source_page_number: 4,
        source_chunk_id: CHUNK_NTW_PROFILES,
        image_url: null,
        caption: '5400mm grooved board cross-section',
        alt_text: 'Cross-section diagram of Avenue Grooved Board',
        suggested_usage: 'product_profile',
        entity_temp_key: 'profile_0',
        confidence: 0.80,
        parser_note: 'Technical cross-section diagram — good candidate for profile image.',
      },
      {
        // Component/accessory image candidate
        source_document_id: DOC_NTW,
        source_page_number: 8,
        source_chunk_id: CHUNK_NTW_CLIPS,
        image_url: null,
        caption: 'TC28 clip installation detail',
        alt_text: 'TC28 hidden fix clip',
        suggested_usage: 'component_accessory',
        entity_temp_key: 'component_0',
        confidence: 0.82,
        parser_note: null,
      },
      {
        // Installation diagram candidate
        source_document_id: DOC_NTW,
        source_page_number: 11,
        source_chunk_id: CHUNK_NTW_CLIPS,
        image_url: null,
        caption: 'Decking joist and clip spacing diagram',
        alt_text: 'Installation diagram showing clip and board spacing',
        suggested_usage: 'installation_detail',
        entity_temp_key: 'system_0',
        confidence: 0.88,
        parser_note: null,
      },
    ],
  },

  warnings: [],
  ignored_content_notes: [
    'Pages 12–14 identified as marketing/lifestyle photography — not extracted.',
    'Warranty terms section skipped — not product data.',
  ],
}

// ----------------------------------------------------------
// Fixture 2: James Hardie Linea Weatherboard (fibre cement cladding)
//
// Exercises:
//   - thickness_mm (not height_mm) for board/sheet products
//   - profile-specific BAL rating
//   - component screws with gauge_mm uncertainty
// ----------------------------------------------------------

export const mockJHLinea: ParserOutput = {
  source_document_id: DOC_JH,

  systems: [
    {
      temp_key: 'system_0',
      source_document_id: DOC_JH,
      source_chunk_id: CHUNK_JH_COVER,
      source_page_number: 1,
      name: 'Linea Weatherboard',
      product_code: null,
      slug: null,
      category: 'Cladding',
      subcategory: 'Fibre Cement',
      description:
        'Primed fibre cement weatherboard for external wall cladding.',
      bal_rating: null,
      acoustic_rating: null,
      moisture_resistant: true,
      structural_grade: null,
      double_sided: false,
      sheet_format: null,
      install_guide_urls: null,
      tech_data_url: null,
      notes: 'Suitable for BAL-12.5 and below unless profile-specific BAL rating stated.',
      sort_order: 0,
      extraction_confidence: 0.91,
      field_sources: [
        src('name', 'Linea Weatherboard', 1, CHUNK_JH_COVER, 0.95),
        src('category', 'Cladding', 1, CHUNK_JH_COVER, 0.93),
        src('subcategory', 'Fibre Cement', 1, CHUNK_JH_COVER, 0.89),
        src('moisture_resistant', 'true', 2, CHUNK_JH_COVER, 0.80),
        src('notes', 'Suitable for BAL-12.5 and below unless profile-specific BAL rating stated.', 3, CHUNK_JH_COVER, 0.82),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
  ],

  system_profiles: [
    {
      // 180mm exposure board — thickness_mm, not height_mm
      temp_key: 'profile_0',
      system_match: { system_name: 'Linea Weatherboard', product_code: null },
      name: 'Linea 180 Weatherboard 4800mm',
      profile_name: 'Linea 180',
      product_code: 'H4040180',
      dimensions: '4800 x 180 x 11 mm',
      length_mm: 4800,
      width_mm: 180,
      thickness_mm: 11,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: 9.1,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      uom: 'lm',
      pack_format: 'Bundle',
      supplier_pack_qty: 8,
      supplier_pack_uom: 'boards',
      supplier_pack_note: null,
      bal_rating: 'BAL-12.5',
      sort_order: 0,
      source_page_number: 3,
      source_chunk_id: CHUNK_JH_PROFILES,
      extraction_confidence: 0.93,
      field_sources: [
        src('profile_name', 'Linea 180', 3, CHUNK_JH_PROFILES, 0.95),
        src('product_code', 'H4040180', 3, CHUNK_JH_PROFILES, 0.97),
        src('length_mm', '4800', 3, CHUNK_JH_PROFILES, 0.97),
        src('width_mm', '180', 3, CHUNK_JH_PROFILES, 0.97),
        src('thickness_mm', '11', 3, CHUNK_JH_PROFILES, 0.96),
        src('uom', 'lm', 3, CHUNK_JH_PROFILES, 0.87),
        src('supplier_pack_qty', '8', 4, CHUNK_JH_PROFILES, 0.88),
        src('supplier_pack_uom', 'boards', 4, CHUNK_JH_PROFILES, 0.85),
        src('bal_rating', 'BAL-12.5', 5, CHUNK_JH_PROFILES, 0.92),
        src('weight_kg', '9.1', 3, CHUNK_JH_PROFILES, 0.83),
      ],
      parser_notes: [
        'Dimensions 4800 x 180 x 11 mm: length_mm=4800, width_mm=180, thickness_mm=11. height_mm left null — source does not label any axis as height.',
      ],
      uncertain_fields: [],
    },
    {
      temp_key: 'profile_1',
      system_match: { system_name: 'Linea Weatherboard', product_code: null },
      name: 'Linea 230 Weatherboard 4800mm',
      profile_name: 'Linea 230',
      product_code: 'H4040230',
      dimensions: '4800 x 230 x 11 mm',
      length_mm: 4800,
      width_mm: 230,
      thickness_mm: 11,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: 11.2,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      uom: 'lm',
      pack_format: 'Bundle',
      supplier_pack_qty: 6,
      supplier_pack_uom: 'boards',
      supplier_pack_note: null,
      bal_rating: 'BAL-12.5',
      sort_order: 1,
      source_page_number: 3,
      source_chunk_id: CHUNK_JH_PROFILES,
      extraction_confidence: 0.92,
      field_sources: [
        src('profile_name', 'Linea 230', 3, CHUNK_JH_PROFILES, 0.94),
        src('product_code', 'H4040230', 3, CHUNK_JH_PROFILES, 0.96),
        src('length_mm', '4800', 3, CHUNK_JH_PROFILES, 0.97),
        src('width_mm', '230', 3, CHUNK_JH_PROFILES, 0.97),
        src('thickness_mm', '11', 3, CHUNK_JH_PROFILES, 0.96),
        src('uom', 'lm', 3, CHUNK_JH_PROFILES, 0.87),
        src('supplier_pack_qty', '6', 4, CHUNK_JH_PROFILES, 0.87),
        src('bal_rating', 'BAL-12.5', 5, CHUNK_JH_PROFILES, 0.92),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
  ],

  components: [
    {
      temp_key: 'component_0',
      source_document_id: DOC_JH,
      source_chunk_id: CHUNK_JH_SCREWS,
      source_page_number: 7,
      sku: 'JH-HDRIVE-50',
      name: 'HardieDrive Screw 50mm',
      description: 'Corrosion-resistant self-drilling screw for fibre cement weatherboard fixing.',
      category: 'Fixings',
      uom: 'ea',
      dimensions: '50mm x 8g',
      length_mm: 50,
      gauge_mm: 8,
      width_mm: null,
      height_mm: null,
      thickness_mm: null,
      depth_mm: null,
      diameter_mm: null,
      roll_m: null,
      weight_kg: null,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      length_m: null,
      pack_format: 'Box',
      supplier_pack_qty: 250,
      supplier_pack_uom: 'screws',
      supplier_pack_note: null,
      material: null,
      finish: null,
      colour: null,
      profile: null,
      texture: null,
      coverage_m2: null,
      sort_order: 0,
      extraction_confidence: 0.86,
      field_sources: [
        src('name', 'HardieDrive Screw 50mm', 7, CHUNK_JH_SCREWS, 0.93),
        src('sku', 'JH-HDRIVE-50', 7, CHUNK_JH_SCREWS, 0.91),
        src('uom', 'ea', 7, CHUNK_JH_SCREWS, 0.85),
        src('length_mm', '50', 7, CHUNK_JH_SCREWS, 0.92),
        src('gauge_mm', '8', 7, CHUNK_JH_SCREWS, 0.74, {
          is_uncertain: true,
          parser_note: 'Source states "8g" — gauge label only, not mm. Flagged uncertain.',
        }),
        src('supplier_pack_qty', '250', 7, CHUNK_JH_SCREWS, 0.91),
        src('supplier_pack_uom', 'screws', 7, CHUNK_JH_SCREWS, 0.89),
      ],
      parser_notes: [
        'gauge_mm=8 from "8g" — gauge label, not a millimetre value. Reviewer should confirm.',
      ],
      uncertain_fields: ['gauge_mm'],
    },
  ],

  system_components: [
    {
      temp_key: 'link_0',
      staged_system_match: { system_name: 'Linea Weatherboard', product_code: null },
      component_match: { sku: 'JH-HDRIVE-50', name: 'HardieDrive Screw 50mm' },
      role: 'required',
      notes: 'Proprietary screw required for fibre cement fixing. Category: Fixings.',
      sort_order: 0,
      extraction_confidence: 0.87,
      source_page_number: 7,
      source_chunk_id: CHUNK_JH_SCREWS,
    },
  ],

  system_colours: [],

  media: {
    images: [
      {
        source_document_id: DOC_JH,
        source_page_number: 1,
        source_chunk_id: CHUNK_JH_COVER,
        image_url: null,
        caption: 'Linea Weatherboard installed on two-storey home',
        alt_text: 'James Hardie Linea Weatherboard exterior cladding',
        suggested_usage: 'hero_system',
        entity_temp_key: 'system_0',
        confidence: 0.83,
        parser_note: null,
      },
      {
        source_document_id: DOC_JH,
        source_page_number: 3,
        source_chunk_id: CHUNK_JH_PROFILES,
        image_url: null,
        caption: 'Linea 180 board profile cross-section',
        alt_text: 'Cross-section of Linea 180 fibre cement weatherboard',
        suggested_usage: 'product_profile',
        entity_temp_key: 'profile_0',
        confidence: 0.81,
        parser_note: null,
      },
    ],
  },

  warnings: [],
  ignored_content_notes: [
    'Colour range pages not present in this document version — no colours extracted.',
  ],
}

// ----------------------------------------------------------
// Fixture 3: Enviroseal ProctorWrap Climate Wrap (roll product)
//
// Exercises:
//   - roll product: roll_m and width_mm as primary dimensions
//   - no length_mm / thickness_mm for the roll profile
//   - accessories (tape) as components
//   - low-confidence uom where source is ambiguous
// ----------------------------------------------------------

export const mockEnviroSealWrap: ParserOutput = {
  source_document_id: DOC_WRAP,

  systems: [
    {
      temp_key: 'system_0',
      source_document_id: DOC_WRAP,
      source_chunk_id: CHUNK_WRAP_COVER,
      source_page_number: 1,
      name: 'ProctorWrap 60',
      product_code: 'PW60',
      slug: null,
      category: 'Building Wrap',
      subcategory: 'Climate Control',
      description:
        'Vapour-permeable, water-resistant building wrap for wall and roof sarking applications.',
      bal_rating: null,
      acoustic_rating: null,
      moisture_resistant: true,
      structural_grade: null,
      double_sided: false,
      sheet_format: null,
      install_guide_urls: null,
      tech_data_url: null,
      notes: null,
      sort_order: 0,
      extraction_confidence: 0.90,
      field_sources: [
        src('name', 'ProctorWrap 60', 1, CHUNK_WRAP_COVER, 0.95),
        src('product_code', 'PW60', 1, CHUNK_WRAP_COVER, 0.92),
        src('category', 'Building Wrap', 1, CHUNK_WRAP_COVER, 0.89),
        src('subcategory', 'Climate Control', 1, CHUNK_WRAP_COVER, 0.82),
        src('description', 'Vapour-permeable, water-resistant building wrap for wall and roof sarking applications.', 1, CHUNK_WRAP_COVER, 0.85),
        src('moisture_resistant', 'true', 2, CHUNK_WRAP_COVER, 0.88),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
  ],

  system_profiles: [
    {
      // 2700mm wide, 50m roll — roll_m is the primary dimension
      temp_key: 'profile_0',
      system_match: { system_name: 'ProctorWrap 60', product_code: 'PW60' },
      name: 'ProctorWrap 60 — 2700mm × 50m Roll',
      profile_name: '2700mm 50m Roll',
      product_code: 'PW60-2700',
      dimensions: '2700 mm wide × 50 m roll',
      length_mm: null,
      width_mm: 2700,
      roll_m: 50,
      thickness_mm: null,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      length_m: null,
      weight_kg: 11.5,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      uom: 'roll',
      pack_format: 'Roll',
      supplier_pack_qty: null,
      supplier_pack_uom: null,
      supplier_pack_note: null,
      bal_rating: null,
      sort_order: 0,
      source_page_number: 3,
      source_chunk_id: CHUNK_WRAP_SPECS,
      extraction_confidence: 0.88,
      field_sources: [
        src('profile_name', '2700mm 50m Roll', 3, CHUNK_WRAP_SPECS, 0.90),
        src('product_code', 'PW60-2700', 3, CHUNK_WRAP_SPECS, 0.91),
        src('width_mm', '2700', 3, CHUNK_WRAP_SPECS, 0.96),
        src('roll_m', '50', 3, CHUNK_WRAP_SPECS, 0.96),
        src('uom', 'roll', 3, CHUNK_WRAP_SPECS, 0.88),
        src('weight_kg', '11.5', 3, CHUNK_WRAP_SPECS, 0.82),
      ],
      parser_notes: [
        'Roll product: primary dimensions are width_mm and roll_m. length_mm and thickness_mm left null.',
      ],
      uncertain_fields: [],
    },
    {
      // 1350mm wide, 50m roll — narrower width variant
      temp_key: 'profile_1',
      system_match: { system_name: 'ProctorWrap 60', product_code: 'PW60' },
      name: 'ProctorWrap 60 — 1350mm × 50m Roll',
      profile_name: '1350mm 50m Roll',
      product_code: 'PW60-1350',
      dimensions: '1350 mm wide × 50 m roll',
      length_mm: null,
      width_mm: 1350,
      roll_m: 50,
      thickness_mm: null,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      length_m: null,
      weight_kg: null,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      uom: 'roll',
      pack_format: 'Roll',
      supplier_pack_qty: null,
      supplier_pack_uom: null,
      supplier_pack_note: 'Minimum 2 roll order stated in price list',
      bal_rating: null,
      sort_order: 1,
      source_page_number: 3,
      source_chunk_id: CHUNK_WRAP_SPECS,
      extraction_confidence: 0.85,
      field_sources: [
        src('profile_name', '1350mm 50m Roll', 3, CHUNK_WRAP_SPECS, 0.88),
        src('product_code', 'PW60-1350', 3, CHUNK_WRAP_SPECS, 0.90),
        src('width_mm', '1350', 3, CHUNK_WRAP_SPECS, 0.96),
        src('roll_m', '50', 3, CHUNK_WRAP_SPECS, 0.96),
        src('uom', 'roll', 3, CHUNK_WRAP_SPECS, 0.87),
        src('supplier_pack_note', 'Minimum 2 roll order stated in price list', 4, CHUNK_WRAP_SPECS, 0.79, {
          is_uncertain: true,
          parser_note: 'Minimum order stated in distributor price list supplement — may not apply to all suppliers.',
        }),
      ],
      parser_notes: [],
      uncertain_fields: ['supplier_pack_note'],
    },
  ],

  components: [
    {
      // Sealing tape — component/accessory for the wrap system
      temp_key: 'component_0',
      source_document_id: DOC_WRAP,
      source_chunk_id: CHUNK_WRAP_TAPE,
      source_page_number: 6,
      sku: 'PW-TAPE-75',
      name: 'ProctorWrap Sealing Tape 75mm',
      description: 'Self-adhesive sealing tape for ProctorWrap overlaps and penetrations.',
      category: 'Tapes',
      uom: 'roll',
      dimensions: '75 mm wide × 25 m roll',
      length_mm: null,
      width_mm: 75,
      roll_m: 25,
      thickness_mm: null,
      height_mm: null,
      depth_mm: null,
      gauge_mm: null,
      diameter_mm: null,
      length_m: null,
      weight_kg: null,
      weight_g: null,
      volume_ml: null,
      pieces: null,
      pack_format: 'Roll',
      supplier_pack_qty: 6,
      supplier_pack_uom: 'rolls',
      supplier_pack_note: null,
      material: null,
      finish: null,
      colour: null,
      profile: null,
      texture: null,
      coverage_m2: null,
      sort_order: 0,
      extraction_confidence: 0.87,
      field_sources: [
        src('name', 'ProctorWrap Sealing Tape 75mm', 6, CHUNK_WRAP_TAPE, 0.93),
        src('sku', 'PW-TAPE-75', 6, CHUNK_WRAP_TAPE, 0.91),
        src('category', 'Tapes', 6, CHUNK_WRAP_TAPE, 0.88),
        src('uom', 'roll', 6, CHUNK_WRAP_TAPE, 0.85),
        src('width_mm', '75', 6, CHUNK_WRAP_TAPE, 0.94),
        src('roll_m', '25', 6, CHUNK_WRAP_TAPE, 0.93),
        src('supplier_pack_qty', '6', 6, CHUNK_WRAP_TAPE, 0.88),
        src('supplier_pack_uom', 'rolls', 6, CHUNK_WRAP_TAPE, 0.86),
      ],
      parser_notes: [],
      uncertain_fields: [],
    },
  ],

  system_components: [
    {
      temp_key: 'link_0',
      staged_system_match: { system_name: 'ProctorWrap 60', product_code: 'PW60' },
      component_match: { sku: 'PW-TAPE-75', name: 'ProctorWrap Sealing Tape 75mm' },
      role: 'required',
      notes: 'Required for sealing overlaps and penetrations. Category: Tapes.',
      sort_order: 0,
      extraction_confidence: 0.86,
      source_page_number: 6,
      source_chunk_id: CHUNK_WRAP_TAPE,
    },
  ],

  system_colours: [],

  media: {
    images: [
      {
        source_document_id: DOC_WRAP,
        source_page_number: 1,
        source_chunk_id: CHUNK_WRAP_COVER,
        image_url: null,
        caption: 'ProctorWrap 60 installed on timber frame wall',
        alt_text: 'Enviroseal ProctorWrap 60 building wrap installation',
        suggested_usage: 'hero_system',
        entity_temp_key: 'system_0',
        confidence: 0.80,
        parser_note: null,
      },
      {
        source_document_id: DOC_WRAP,
        source_page_number: 6,
        source_chunk_id: CHUNK_WRAP_TAPE,
        image_url: null,
        caption: 'Tape application at wrap overlap joint',
        alt_text: 'ProctorWrap sealing tape application detail',
        suggested_usage: 'installation_detail',
        entity_temp_key: 'component_0',
        confidence: 0.83,
        parser_note: null,
      },
    ],
  },

  warnings: [
    'Product code PW60-1350 not confirmed — derived from width variant; reviewer should verify against price list.',
  ],
  ignored_content_notes: [
    'Technical specification table for vapour permeability and tensile strength not extracted — no matching schema fields.',
    'Installation video QR code found on page 5 — URL not extracted.',
  ],
}

// ----------------------------------------------------------
// All fixtures as an array — useful for testing the insertion layer
// against the full range of entity types and edge cases.
// ----------------------------------------------------------

export const allMockFixtures: ParserOutput[] = [
  mockNTWAvenueDecking,
  mockJHLinea,
  mockEnviroSealWrap,
]
