-- BuildQuote Data Studio — Migration 067
-- Per-document AI summary — design doc ADDENDUM 3 §C6 ("per-document-type
-- JSON-LD summaries"), un-deferred per explicit instruction ("no need to
-- defer anything — do the full implementation").
--
-- Not run against this environment by this session — no live Supabase
-- credentials are available here. Apply manually in the Supabase SQL editor
-- against the Data Studio project (ovndokzwkxpfjfobewaq), same as
-- migrations 065/066, then:
--   node scripts/refresh_schema_reference.mjs
--
-- Never run against the RFQ production project (oxvhmulxuvlfjyjzleki).
--
-- Additive only. A short synopsis of what one whole linked document (an
-- install guide, a design guide, a tech data sheet) covers for one system —
-- distinct from the discrete knowledge_assertions facts the knowledge
-- parser already extracts from it, and distinct from the existing
-- claim-type-grouped bq:retrievalDocuments[] (design doc §5a.4). Generated
-- once per (system, document) by run_knowledge_parser.py alongside its
-- normal fact extraction (one extra Claude call per document, not per
-- chunk), stored here rather than recomputed on every knowledge.jsonld
-- request.

ALTER TABLE public.system_sources
  ADD COLUMN IF NOT EXISTS ai_summary TEXT,
  ADD COLUMN IF NOT EXISTS ai_summary_generated_at TIMESTAMPTZ;

COMMENT ON COLUMN public.system_sources.ai_summary IS
  'Short (2-4 sentence) synopsis of what this document covers for this system, generated by run_knowledge_parser.py. NULL until the knowledge parser has run for this source. Never hand-edited — a stale summary is refreshed by re-running extraction, not corrected in place.';
COMMENT ON COLUMN public.system_sources.ai_summary_generated_at IS
  'When ai_summary was last (re)generated. NULL until first generation.';
